version: '3'

services:

  frontend: anilagad/frontend-tier-image:latest
    image: 
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: anilagad/backend-tier-image:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://username:password@database:5432/db_name
    depends_on:
      - database

  database:
    image: anilagad/database-tier-image
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
