name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-app-nginx:latest .

    - name: Tag Docker image
      run: docker tag my-app-nginx:latest anilagad/my-app-nginx:latest

    - name: Push Docker image
      run: docker push anilagad/my-app-nginx:latest
